<?php
require_once("Includes/db.php");
session_start();

if ($_SERVER['REQUEST_METHOD'] == "POST") {
        // Automatically create a provisional account 
        $autogeneratedPW = "nrgfoods";
        echo $_POST['email'];
		munchKitDB::getInstance()->create_user($_POST['email'], $autogeneratedPW, $_POST['firstName'], $_POST['lastName'], $_POST['phone'], $_POST['streetAddress'], $_POST['city'], $_POST['prov'], $_POST['zipCode']); 

        //Retrieve the id from the account just created to add munchkids to this account
        $userID = munchKitDB::getInstance()->get_user_id_by_email($_POST['email']);

        echo $userID;
        // Add MunchKids to this parent's account
        $numKids = $_POST['numKids'];
        $i = 1;
        while($numKids >= $i){

            $allergies= '';
            foreach($_POST['allergies_'.$i] as $allergy){
                $allergies .= $allergy. ',';
            }

            munchKitDB::getInstance()->insert_munchkid($userID, $_POST['f_name_'.$i], $_POST['dietType_'.$i], $allergies, $_POST['additionalNotes_'.$i]);

            //To pass the variable values to order_summary
            // child info
            $_SESSION['f_name_'.$i] = $_POST['f_name_'.$i];
            $_SESSION['dietType_'.$i] = $_POST['dietType_'.$i];
            $_SESSION['allergies_'.$i] = $allergies;
            $_SESSION['additionalNotes_'.$i] = $_POST['additionalNotes_'.$i];
            $_SESSION['mealplan_'.$i] = $_POST['mealplan_'.$i];

            $i++;
        }

        // end of adding munchkids
        // Add provisional orders for each munchkid that was just created
        $result= munchKitDB::getInstance()->get_munchkids_by_user_email($_POST['email']);
            echo $numKids;
            echo $i;
         $i=1;
         echo $i;
        if($result != NULL){
            while ($row = $result->fetch_assoc()) {
                if($numKids>=$i){
                    $idMunchKid = $row['idMunchKids'];
                    echo 'munchkid id :'. $idMunchKid;
                    munchKitDB::getInstance()->insert_order($idMunchKid, $_POST['mealplan_'.$i]);
                    $i++;
                }
            }
        }

        //To pass the variable values to order_summary
        // parent user info
        $_SESSION['email'] = $_POST['email'];
        $_SESSION['firstName'] = $_POST['firstName'];
        $_SESSION['lastName'] = $_POST['lastName'];
        $_SESSION['phone'] = $_POST['phone'];
        $_SESSION['streetAddress'] = $_POST['streetAddress'];
        $_SESSION['city'] = $_POST['city'];
        $_SESSION['prov'] = $_POST['prov'];
        $_SESSION['zipCode'] = $_POST['zipCode'];
        $_SESSION['numkids'] = $numKids; 
}
    
    //Redirect page to checkout summary
    $dest = 'Location: order_summary.php';
    header($dest);
    exit;   


?>


